// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uuxysimuwjkgjfivoogj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1eHlzaW11d2prZ2pmaXZvb2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMDg2ODMsImV4cCI6MjA5Mjg4NDY4M30.Jvdmd_AlcxYz9--By8h3yYV48aZt6hUG5zmZR884yFE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);