// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cvjspyesngpujjhhtqmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2anNweWVzbmdwdWpqaGh0cW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMDY5MjQsImV4cCI6MjA5Mjg4MjkyNH0.d27l4gbnNwCTD89JXiUSCYHOXVdUAPyFCrSghDlRPGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);